---
title: "Your Title Goes Here"
author: "Your Name Goes Here"
date: "Date Goes Here"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(knitr)
library(reticulate)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(python = reticulate::eng_python, echo = TRUE)
```

```{r global.options, include = FALSE}
knitr::opts_chunk$set(
    cache       = TRUE,     # if TRUE knitr will cache the results to reuse in future knits
    fig.align   = 'center', # how to align graphics in the final doc. 'left', 'right', 'center'
    fig.path    = 'figs/',  # file path to the directory where knitr shall store the graphics files
    #results     = 'asis',   # knitr will pass through results without reformatting them
    echo        = TRUE,     # in FALSE knitr will not display code in the code chunk above it's results
    message     = TRUE,     # if FALSE knitr will not display any messages generated by code
    strip.white = TRUE,     # if FALSE knitr will not remove white spaces at the beg or end of code chunk
    warning     = FALSE)    # if FALSE knitr will not display any warning messages in the final document
```


```{r, include=TRUE}
library(RMySQL)
connection = dbConnect(MySQL(), user='root', password='adminleon', 
                       dbname='world', host='localhost')
```

### 1.1	How many countries became independent in the twentieth century? **(10 points)**

```{sql, connection=connection}


```

```{r, include=TRUE}
# Close the connection
dbDisconnect(connection)
```